## (70 points possible)

Also needs the data files cereal.csv and Pokemon.csv.

# Problem 1: Regular Expressions (20 pts [10,6,4])

Each of these sub-problems requires the use of regular expressions.

a, 10 pts) A recipe website uses the following URL format for its recipes "https://awesomerecipes.com/recipes/abcdefgh-12/recipe-name". Users who post their recipes have unique ids (e.g., "abcdefgh-12") consisting of 8 letters followed by a hyphen and 2 numbers. The recipe name is either a single word or has a single hyphen separating the title, for example, "donuts" or "creme-donuts".

Write a function `extract_user_and_recipe(text)` that returns the unique ID and the recipe name from the URL. Ensure your function can extract all the words in the hyphen separated title.

In [1]:
import re
def extract_user_and_recipe(text):
  pattern = r"/recipes/([a-z]{8}-\d{2})/([a-z-]+)/?$"
  match = re.search(pattern, text)
  if match:
    user_id = match.group(1)
    recipe_name = match.group(2)
    return f"{user_id}, {recipe_name}"
  return "No matches"

In [2]:
# Expect 'abcxyzwv-34, donuts':
text1 = 'https://awesomerecipes.com/recipes/abcxyzwv-34/donuts'
# Expect 'abcxyzwv-34, creme-donuts':
text2 = 'https://awesomerecipes.com/recipes/abcxyzwv-34/creme-donuts'

print(extract_user_and_recipe(text1))
print(extract_user_and_recipe(text2))

abcxyzwv-34, donuts
abcxyzwv-34, creme-donuts

b, 6 pts) A college's IT department has decided to update the unique IDs of their internal database of students and faculty/staff by changing to a new format. The old format consisted of 3 letter FAC for faculty, STA for staff, and STU for student, followed by 9 digits. The new format consists of a single letter, U for faculty/staff and u for students, followed by the original 9 digits. Write a function `convert_id(text)` which accepts as input a university ID and returns the re-formatted ID.

In [6]:
def convert_id(text):
  if re.search(r"^(FAC|STA)(\d{9})", text):
    return re.sub(r"(FAC|STA)(\d{9})", r"U\2", text)
  elif re.search(r"^STU", text):
    return re.sub(r"^STU(\d{9})", r"u\1", text)
  return text

In [7]:
print(convert_id("FAC123456789"))  # Expect 'U123456789'
print(convert_id("STA123456789"))  # Expect 'U123456789'
print(convert_id("STU987654321"))  # Expect 'u987654321'

U123456789
U123456789
u987654321

c, 4 pts) An API (application programming interface) endpoint is a specific URL that allows clients (like web browsers, mobile apps, or other servers) to access specific resources or perform certain actions. API endpoints often have query parameters, for example /data?XML or/users?id=123. Write a function `extract_query(text)` which can extract queries that follow a '?' consisting of either 1 or more alphanumeric characters or 1 or more alphanumeric characters that are followed by an equal sign and a string of 1 or more alphanumeric characters. The return value should be a string.

In [8]:
def extract_query(text):
  pattern_1 = r"\?([a-zA-Z0-9=]+)"
  match = re.search(pattern_1, text)
  if match:
    return match.group(1)
  return ""

In [9]:
print(extract_query("/data?XML"))           # Expect 'XML'
print(extract_query("/users?id=123"))       # Expect 'id=123'
print(extract_query("/search?query=books")) # Output: 'query=books'

XML
id=123
query=books

# Problem 2: Strings and DataFrames (10 pts)

Add a new column to the cereal DataFrame, *Bran perc*, that contains 1 for cereals that contain 100% Bran in the name, 0.5 if the name Bran without 100% is in the name, and 0 otherwise.  You can assume that the 100% comes first in the name, but that Bran could appear anywhere else in the name.

Write a helper function bran_perc(text) first to help you; this should analyze the name and return the relevant number.  Then iterate over df.index to build a list that you can assign to the new column.

In [14]:
import pandas as pd
df = pd.read_csv('cereal.csv', index_col='name')
df.head()

,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating
name,,,,,,,,,,,,,,,
100% Bran,N,C,70,4,1,130,10.0,5.0,6,280,25,3,1.0,0.33,68.402973
100% Natural Bran,Q,C,120,3,5,15,2.0,8.0,8,135,0,3,1.0,1.00,33.983679
All-Bran,K,C,70,4,1,260,9.0,7.0,5,320,25,3,1.0,0.33,59.425505
All-Bran with Extra Fiber,K,C,50,4,0,140,14.0,8.0,0,330,25,3,1.0,0.50,93.704912
Almond Delight,R,C,110,2,2,200,1.0,14.0,8,-1,25,3,1.0,0.75,34.384843

In [20]:
def bran_perc(text):
  if "100% Bran" in text:
    return 1.0
  elif "Bran" in text:
    return 0.5
  else:
    return 0

#bran_perc("All-Bran")
#bran_perc("Almond Delight")

bran_list = []
for name in df.index:
  bran_value = bran_perc(name)
  bran_list.append(bran_value)
df['Bran perc'] = bran_list

In [21]:
df.head() # Should see this working for Bran cereals

,mfr,type,calories,protein,fat,sodium,fiber,carbo,sugars,potass,vitamins,shelf,weight,cups,rating,Bran perc
name,,,,,,,,,,,,,,,,
100% Bran,N,C,70,4,1,130,10.0,5.0,6,280,25,3,1.0,0.33,68.402973,1.0
100% Natural Bran,Q,C,120,3,5,15,2.0,8.0,8,135,0,3,1.0,1.00,33.983679,0.5
All-Bran,K,C,70,4,1,260,9.0,7.0,5,320,25,3,1.0,0.33,59.425505,0.5
All-Bran with Extra Fiber,K,C,50,4,0,140,14.0,8.0,0,330,25,3,1.0,0.50,93.704912,0.5
Almond Delight,R,C,110,2,2,200,1.0,14.0,8,-1,25,3,1.0,0.75,34.384843,0.0

# Problem 3: Counting Pokémon (22 points: 8, 10, 4)

You work for the creators of Pokémon GO, a game where players try to collect odd-looking monsters called Pokémon by venturing to real-life locations.  You got a CSV file with each player's name followed by a list of Pokemon they've captured, but the list could contain duplicates.  The goal is to create a JSON file that maps each player to the *number* of unique Pokemon they've captured.

a) (8 points) Write a function count_pokemon() that takes a comma-separated string of Pokémon names and returns the number of unique Pokémon mentioned.  (Not only could there be duplicates in the string, but there may be whitespace differences that shouldn't matter; be sure to use strip().)

b) (10 points) Write a function pokemon_to_dict() that takes as its only argument the name of a CSV file.  The CSV file has player names in its first column and comma-separated Pokemon lists as its second column (see part a).  (You can assume there is *no* header line that is different from all the others - all the lines contain data in the format described.)  The function should return a dictionary where the keys are player names, and the values are the number of unique Pokémon associated with their player (see part a).

If the file isn't there, a FileNotFoundError should be handled by printing a message that states the particular filename in the argument wasn't found.

A sample Pokémon CSV, Pokemon.csv, has been provided for this part.

c) (4 points) Write a function dict_to_json() that takes a dictionary and a filename as an arguments a dictionary of the kind created in part (b) and an output filename; the function should write the JSON implied by the dictionary to the given filename.

Use the following code box to upload the sample Pokemon.csv file, and include your final code for parts (a)-(c) in the code box after that.

In [23]:
from google.colab import files
files.upload()

Saving Pokemon.csv to Pokemon (1).csv

{'Pokemon (1).csv': b'Alice,"Pikachu,Charizard,Evee,Snorlax,Charmander, Ditto, Sylveon"\r\nBob,"Pikachu, Charizard, Pikachu, Charizard, Sylveon"\r\nCarol,"Ditto, Bulbasaur, Snorlax, Bulbasaur"\r\nDeng,"Squirtle, Mewtwo , Charmander"\r\nEileen,"Snorlax, Pikachu, Pikachu, Sylveon"\r\nFatima,"Lucario, Mew, Garchomp, Bulbasaur, Jigglypuff"\r\n'}

In [35]:
def count_pokemon(text):
  raw_list = text.split(',')
  unique_pokemon = {name.strip() for name in raw_list if name.strip()}
  return len(unique_pokemon)

def pokemon_to_dict(filename):
  poke_dict = {}
  try:
    with open(filename, mode='r') as file:
      reader = csv.reader(file)
      for row in reader:
        player_name = row[0]
        pokemon_string = row[1]
        poke_dict[player_name] = count_pokemon(pokemon_string)
    return poke_dict
  except FileNotFoundError:
    print("The file, {filename},  wasn't found.")
    return None

import csv
import json
def dict_to_json(dictionary, filename):
  with open(filename, 'w') as f:
    json.dump(dictionary, f)

In [36]:
mydict = pokemon_to_dict('Pokemon.csv')
dict_to_json(mydict, 'poke.json')
#!ls
!cat poke.json   # Should be Alice: 7, Bob: 3, Carol: 3, Deng: 3, Eileen: 3, Fatima: 5

{"Alice": 7, "Bob": 3, "Carol": 3, "Deng": 3, "Eileen": 3, "Fatima": 5}

# Problem 4: The radar image class (18 pts [2, 4, 2, 5, 5])

You work for a ship-motion prediction company that needs to create a Python class in order to accumulate continuously streaming radar images. Each radar image is a 2D NumPy array of dimension 10 x 10. The class should be named `RadarImages`. You need to design this class to do the following:

a, 2 pts) Initialize the class with an attribute called `img_list` that is an empty list and an attribute called `max_img_list_size` that is set from an integer `max_img_list_size` passed as an input argument in the class constructor.

b, 4 pts) Implement an `add_radar_image(matrix)` member function which appends a 10x10 2D numpy array to `image_list`. If you call this function and the length of the list is `max_img_list_size` (before appending), remove the 1st element of list and append the new image to the end of the list.

c, 2 pts) Implement a `flush_images()` member function which sets the `img_list` attribute to an empty list.

d, 5 pts) Implement an `average_radar_images()` member function which returns an average image matrix. Specifically, the average image matrix is the sum of all the images in the list divided by the total number of images. If the image list is empty, return a 10x10 matrix of zeros.

e, 5 pts) Implement a `blur_radar_image(matrix, index)` function which takes a 10x10 2D NumPy array and an integer index as input arguments. The function should add the input argument `matrix` to the radar image at position index in the `img_list`. If the index is out of bounds, raise an `IndexError`. The syntax to raise an `IndexError` is `raise IndexError("Index out of bounds")`.

In [69]:
import numpy as np
class RadarImages:
  def __init__(self, max_img_list_size):
    self.image_list = []
    self.max_img_list_size = max_img_list_size

  def add_radar_images(self, matrix):
    if len(self.image_list) == self.max_img_list_size:
      self.image_list.pop(0)
    self.image_list.append(matrix)

  def flush_images(self):
    self.image_list = []

  def average_radar_image(self):
    if not self.image_list:
      return np.zeros((10, 10))
    total_sum = sum(self.image_list)
    return total_sum / len(self.image_list)

  def blur_radar_image(self, matrix, index):
    try:
      self.image_list[index] = self.image_list[index] + matrix
    except IndexError:
      raise IndexError("Index out of bounds")

In [70]:
import numpy as np

radar_images = RadarImages(5)
rng = np.random.default_rng(42)
image1 = rng.random((10, 10))
image2 = rng.random((10, 10))
image3 = rng.random((10, 10))
image4 = rng.random((10, 10))
image5 = rng.random((10, 10))
image6 = rng.random((10, 10))

# TEST 1 should print 10 x 10 matrix of zeros and returns True if the returned array is equal to matrix of zeros
print(radar_images.average_radar_image())
print(np.array_equal(np.zeros((10, 10)), radar_images.average_radar_image()))

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
True

In [71]:
radar_images.add_radar_images(image1)
# TEST 2 should print 10 x 10 matrix that is the same as image1 and returns True if the returned array is equal to image 1
print(radar_images.average_radar_image())
print (np.array_equal(image1, radar_images.average_radar_image()))

[[0.77395605 0.43887844 0.85859792 0.69736803 0.09417735 0.97562235
  0.7611397  0.78606431 0.12811363 0.45038594]
 [0.37079802 0.92676499 0.64386512 0.82276161 0.4434142  0.22723872
  0.55458479 0.06381726 0.82763117 0.6316644 ]
 [0.75808774 0.35452597 0.97069802 0.89312112 0.7783835  0.19463871
  0.466721   0.04380377 0.15428949 0.68304895]
 [0.74476216 0.96750973 0.32582536 0.37045971 0.46955581 0.18947136
  0.12992151 0.47570493 0.22690935 0.66981399]
 [0.43715192 0.8326782  0.7002651  0.31236664 0.8322598  0.80476436
  0.38747838 0.2883281  0.6824955  0.13975248]
 [0.1999082  0.00736227 0.78692438 0.66485086 0.70516538 0.78072903
  0.45891578 0.5687412  0.139797   0.11453007]
 [0.66840296 0.47109621 0.56523611 0.76499886 0.63471832 0.5535794
  0.55920716 0.3039501  0.03081783 0.43671739]
 [0.21458467 0.40852864 0.85340307 0.23393949 0.05830274 0.28138389
  0.29359376 0.66191651 0.55703215 0.78389821]
 [0.66431354 0.40638686 0.81402038 0.16697292 0.02271207 0.09004786
  0.72235935 0.46187723 0.16127178 0.50104478]
 [0.1523121  0.69632038 0.44615628 0.38102123 0.30151209 0.63028259
  0.36181261 0.08764992 0.1180059  0.96189766]]
True

In [72]:
# Test 3 returns True if image 6 is equal to the last image in the image_list
radar_images.add_radar_images(image2)
radar_images.add_radar_images(image3)
radar_images.add_radar_images(image4)
radar_images.add_radar_images(image5)
radar_images.add_radar_images(image6)
print(np.array_equal(image6, radar_images.image_list[-1]))

True

In [73]:
# Test 4 shows an image that is blurred
index = 1
print(radar_images.image_list[index], "\n")

ones = np.ones((10, 10))
radar_images.blur_radar_image(ones, index)
print(radar_images.image_list[index])

[[0.77740484 0.97182643 0.50074119 0.1438975  0.01393629 0.22965603
  0.13182222 0.67765867 0.1218325  0.50632993]
 [0.69426244 0.58111661 0.19977565 0.80412453 0.71540713 0.738984
  0.13105775 0.1237538  0.92756255 0.39757819]
 [0.30094869 0.48858405 0.66286421 0.95562326 0.28644623 0.92480843
  0.02485949 0.55519804 0.63397511 0.1058974 ]
 [0.1403396  0.41911432 0.96623191 0.59604255 0.93302322 0.80436092
  0.4673816  0.78476345 0.01783678 0.109144  ]
 [0.82942861 0.79681709 0.23264074 0.53076959 0.60601582 0.86773895
  0.60310716 0.41257157 0.37418404 0.42588209]
 [0.65193103 0.86749063 0.45389688 0.24783956 0.23666236 0.74601428
  0.81656876 0.10527808 0.06655886 0.59443366]
 [0.14617324 0.82466419 0.31033467 0.14387193 0.92097047 0.16553172
  0.28472008 0.1536134  0.11549006 0.02114802]
 [0.05539541 0.17464147 0.05338193 0.59114382 0.68071453 0.39363046
  0.3179911  0.50452624 0.87500494 0.85113163]
 [0.04347506 0.18149841 0.23674487 0.24938758 0.57123265 0.41626243
  0.04925412 0.37361414 0.52375295 0.1016719 ]
 [0.83345855 0.05196187 0.92484187 0.09911314 0.84357495 0.90265314
  0.97957068 0.80202588 0.77947754 0.64248328]]

[[1.77740484 1.97182643 1.50074119 1.1438975  1.01393629 1.22965603
  1.13182222 1.67765867 1.1218325  1.50632993]
 [1.69426244 1.58111661 1.19977565 1.80412453 1.71540713 1.738984
  1.13105775 1.1237538  1.92756255 1.39757819]
 [1.30094869 1.48858405 1.66286421 1.95562326 1.28644623 1.92480843
  1.02485949 1.55519804 1.63397511 1.1058974 ]
 [1.1403396  1.41911432 1.96623191 1.59604255 1.93302322 1.80436092
  1.4673816  1.78476345 1.01783678 1.109144  ]
 [1.82942861 1.79681709 1.23264074 1.53076959 1.60601582 1.86773895
  1.60310716 1.41257157 1.37418404 1.42588209]
 [1.65193103 1.86749063 1.45389688 1.24783956 1.23666236 1.74601428
  1.81656876 1.10527808 1.06655886 1.59443366]
 [1.14617324 1.82466419 1.31033467 1.14387193 1.92097047 1.16553172
  1.28472008 1.1536134  1.11549006 1.02114802]
 [1.05539541 1.17464147 1.05338193 1.59114382 1.68071453 1.39363046
  1.3179911  1.50452624 1.87500494 1.85113163]
 [1.04347506 1.18149841 1.23674487 1.24938758 1.57123265 1.41626243
  1.04925412 1.37361414 1.52375295 1.1016719 ]
 [1.83345855 1.05196187 1.92484187 1.09911314 1.84357495 1.90265314
  1.97957068 1.80202588 1.77947754 1.64248328]]

In [74]:
# Test 5 returns True if the length of image_list is 0 after flushing
radar_images.flush_images()
print(len(radar_images.image_list) == 0)

True

In [75]:
# Test 6 raises an IndexError
index = 5
radar_images.blur_radar_image(ones, index)

IndexError: Index out of bounds